### ISSUE TITLE
[ BUG ] Cannot Be Installed via BRAT

### ISSUE THREAD

**Issue by StefanoRausch** [Fevol/obsidian-translate#1]
![0B3F3C91-3D3C-4EA2-814E-09A836595BD1](https://user-images.githubusercontent.com/1460531/173238337-dd18047e-272b-4ce8-8c6f-ffd1c68e2f0d.jpeg)

**Comment by Fevol** [comment]
My apologies, it seems that I didn't properly test the BRAT release, I'll be more careful of that in the future!
If you encounter any other issues, please let me know!

**Comment by StefanoRausch** [comment]
Thanks!
