### ISSUE TITLE
[feat] Support dragging pop-out windows back

### ISSUE THREAD

**Issue by kometenstaub** [Fevol/obsidian-translate#20]
Currently, the view gets attached to the containerEl. It has the effect that when dragging the sidebar view outside of the main window or into the root split of the main window, that there is no way to drag it back.

I would have made a PR, but as is visible in the second picture, the resizing is off when using contentEl and would need to be adjusted.

Current containerEl implementation:

![current implementation](https://user-images.githubusercontent.com/83140328/175776004-0159a32f-5501-4d6e-98f1-1eeeed5fc063.png)

When using contentEl:

![contentEl implementation](https://user-images.githubusercontent.com/83140328/175776030-8ec4bae6-1462-45fe-8565-29926bba51c2.png)

**Comment by Fevol** [comment]
Should be easy to fix, resizing is probably off due to the size of the containerEl being taken instead of contentEl (though will have to check that), will be adding it soon!

**Comment by Fevol** [comment]
I should be a bit more careful with my hubris, it took me a while to find the culprit
Solved the sizing issue and added the contentEl in the latest commits, but will only be releasing once I've triple-checked that the new security measures work, should be later today... if nothing goes wrong

**Comment by kometenstaub** [comment]
Thank you :purple_heart:

**Comment by kometenstaub** [comment]
Thanks for implementing it!
