### ISSUE TITLE
Translation view: Button for copying the translated text

### ISSUE THREAD

**Issue by TfTHacker** [Fevol/obsidian-translate#31]
It would be nice to have a button in the Translation view for copying the text from the translated text portion of the view.

Additionally, it would be good to have a shortcut key for the button.

Tnx!

**Comment by Fevol** [comment]
Sorry for the long wait, in the most recent commits, I've added a way for the user to customize the translation view by adding 'quickbuttons' to either of the text areas (see the GIF below). 

If you have any suggestions/feedback, do let me know! Currently, the buttons do not have any shortcut attached to them, as it would be pretty difficult to implement that to the quickbuttons in a clean way. Would this be a big issue for you?

![appearance-modal-full](https://user-images.githubusercontent.com/8179397/193179459-043189de-3050-4f35-9b20-d3772638cad4.gif)

**Comment by Fevol** [comment]
This functionality is now included in the 1.4.0 beta, quickactions are added by default when opening a new translation view, but you can also change the following things:
1. Assign quicksettings quickactions per individual translation view via the **'appearance settings modal'** (enable `Appearance > Advanced > Show tab title bar` to gain access to the button)
2. Change the default quicksettings that will be added when opening a new translation view in `Plugin Settings > Appearance > Translation View Defaults`
3. Assign hotkeys to the quickactions in `Plugin Settings > Hotkeys`, when **focusing** (previously, command would be able to be triggered on hover) on a textarea, you can execute the hotkey.

**Comment by Fevol** [comment]
Going to be closing this issue, as this feature has been fully released now. Let me know if there are some more types of action that should be included!
