### ISSUE TITLE
Translation view: define default languages

### ISSUE THREAD

**Issue by TfTHacker** [Fevol/obsidian-translate#32]
Enjoying Obsidian Translate. Thank you for this tool!

It would be useful to assign default languages to the Translation View.  So in settings, I can't say Language 1: is English, and Language 2: is Spanish, and Translation View always opens with those as defaults.

Tnx!

**Comment by Fevol** [comment]
Will be shipped with 1.4.0! The settings will be located in the new `Functionality` tab.
Still debating whether or not to attach other functionalities to those settings, so it's possible it may be moved to another location in the future.
![image](https://user-images.githubusercontent.com/8179397/193189185-c8fcafe1-2fc4-4a17-bc58-6c76153f3120.png)

**Comment by Fevol** [comment]
Going to be closing this issue as the feature has been shipped with 1.4.0. As always, let me know if this feature could be improved!
