### ISSUE TITLE
Crashing after Obsidian update to 1.0.0

### ISSUE THREAD

**Issue by ORBITINGninja** [Fevol/obsidian-translate#33]
Mac M1, macOS Monterey, Version 12.6. Obsidian ver. 1.0.0. 
Switching plugin off and on, helps but eventually it crashes. See picture below.

![SCR-20221023-l14-2](https://user-images.githubusercontent.com/108236030/197395048-118238c6-833d-4b3d-b7e8-c93e7994a9aa.png)

**Comment by ORBITINGninja** [comment]
To reproduce, open a note, choose view-->split down (make sure that view is not split 
 in any way before)

**Comment by Fevol** [comment]
I'm really sorry for getting back to you this late. University has been taking up all my available time, so I wasn't able to work on this plugin at all. I'll take a look in a couple days, hopefully it's something I can fix quickly!

Really sorry again for the inconvenience!

**Comment by Fevol** [comment]
Thanks for the wait! I have not been able to confirm this exact bug occuring, though there definitely are issues with 1.0.0 - I do believe this has alraedy been fixed in an unreleased commit.

I'll try to work on putting an updated version out of the plugin ASAP.

**Comment by Fevol** [comment]
Hey @ORBITINGninja, sorry for the month-long wait!
I've released the 1.4.0-beta update, which you can find in releases/install via BRAT, please do let me know if this problem still persists with the new release: a lot of systems were rewritten, so it's quite possible that it has been resolved.

In the future, I'll try to get to resolving these bugs sooner!

**Comment by Fevol** [comment]
@ORBITINGninja I've marked the issue as stale for now.  As mentioned before, I haven't been able to reproduce your error, and can thus not verify whether the bug is properly fixed. So, if you have the time, please do let me know if the issue has been fixed. Many thanks!
