### ISSUE TITLE
Feature request + Bug: DeepL & Google Translate free alternative / Fanyi Youdao validation issues

### ISSUE THREAD

**Issue by jiangaq** [Fevol/obsidian-translate#35]
Thank you.

**Comment by Fevol** [comment]
Thank you for the feature request!

Officially speaking, there is no _fully_ free choice for either DeepL or Google Translate, unless you've signed up for their API.

The plugin does include [LingvaTranslate](https://github.com/thedaviddelta/lingva-translate), which is a freely accessible Google Translate scraper (i.e. does not require sign-up), it should work out of the box -- though you may have to switch hosts to get the one that works best for you (or host the service yourself using Docker/Vercel).

As for DeepL, I can't immediately find any scrapers that work reliably and could also be added to the plugin easily. If the LingvaTranslate service doesn't work for you, I'm afraid the only other option would be to embed the websites as iframes, though I haven't tried that method myself.

**Comment by jiangaq** [comment]
Thank you for your explain.

However, I have youdao api, but it doesn't work, showing "Translation service is not validated".

When testing in setting, it shows "Validation failed: undefined".

Could you please check?

**Comment by Fevol** [comment]
Many thanks for pointing that out, it seems that the error code was not being shown properly. Something else does seem to be wrong with the validation request.

If you don't mind, could you download the below this, and unpack it in `.obsidian/plugins/translate`? Then _validate_ the service again and see what error code it gives, that would be immensely helpful!
https://github.com/Fevol/obsidian-translate/files/10358832/translate.zip

**Comment by jiangaq** [comment]
Tried, it shows "Validation failed: 202" now, what does that mean?

**Comment by Fevol** [comment]
According to Youdao's [API docs](https://ai.youdao.com/DOCSIRMA/html/%E8%87%AA%E7%84%B6%E8%AF%AD%E8%A8%80%E7%BF%BB%E8%AF%91/API%E6%96%87%E6%A1%A3/%E6%96%87%E6%9C%AC%E7%BF%BB%E8%AF%91%E6%9C%8D%E5%8A%A1/%E6%96%87%E6%9C%AC%E7%BF%BB%E8%AF%91%E6%9C%8D%E5%8A%A1-API%E6%96%87%E6%A1%A3.html#:~:text=URLDecode%E7%9A%84%E9%94%99%E8%AF%AF-,202,-%E7%AD%BE%E5%90%8D%E6%A3%80%E9%AA%8C%E5%A4%B1%E8%B4%A5), it looks like the signature verification is failing due to an encoding problem. I'm not sure why that is happening, but I'll try to fix the issue ASAP.

**Comment by Fevol** [comment]
Looks like I made a few tiny mistakes with the signature procedure, could you check if it works now? 

New attempt:
https://github.com/Fevol/obsidian-translate/files/10359308/translate.zip

**Comment by jiangaq** [comment]
Now returned ""Validation failed:0"

**Comment by Fevol** [comment]
Alright, after double-checking, that means that the request was correctly sent and retrieved, so all functions seem to work properly.

Had to fix one last issue, but with this, you should be able to validate the service and translate text now.

Fixed version: https://github.com/Fevol/obsidian-translate/files/10359449/translate.zip

I'm really grateful for all your help with debugging this issue!

**Comment by Fevol** [comment]
Sorry, I've uploaded the wrong version, this is the actual fix:
https://github.com/Fevol/obsidian-translate/files/10359484/translate.zip

**Comment by jiangaq** [comment]
It works now, thank you so much!

**Comment by Fevol** [comment]
Incredibly glad to hear that! If you find any issues related to Youdao (or anything else), do let me know. 
I'll try pushing an official fix later today, which will hopefully also improve the error messaging. 

Again, thank you for helping me debug this!

**Comment by Fevol** [comment]
I'm going to mark this as closed for now. If you (or anybody else) would like to suggest a DeepL scraper alternative for the plugin, please open up a new feature request issue.
