### ISSUE TITLE
[BUG] FastText not in Filter Services

### ISSUE THREAD

**Issue by davidjaggi** [Fevol/obsidian-translate#40]
# User report
**Description:** Fast Text cannot be selected as the option filter services does not contain the item.

---
# Debugger data (do not alter)
**plugin_version**: "1.4.4"
**platform**: "Desktop"
**framework_version**: "1.1.9"
**obsidian_version**: "1.1.12"
**selected_service**: "deepl"

**Comment by Fevol** [comment]
Thanks for the feedback! 

I'll include an option to also allow FastText to be filtered, but it'll have to be in the next release (which will be about two weeks from now, I'm currently a bit busy with other work).

**Comment by Fevol** [comment]
I apologise for the very long wait, in the [latest public release](https://github.com/Fevol/obsidian-translate/releases/tag/1.4.6), you can now also filter/hide FastText.
