### ISSUE TITLE
[BUG] Terms in both directions has no persistance

### ISSUE THREAD

**Issue by andremeireles** [Fevol/obsidian-translate#41]
## Type of change

- [ ] Bug fix

## Description

In Glossary tab, enable the toggle button has no persistance.

> I think is related to that glossary tab too:
> If i fill a glossary term and add it in one direction doesn't fill the reverse pair after click at the "reverse" button.
> So i need fill the two ways.

---
# Debugger data (do not alter)
**plugin_version**: "1.4.4"
**platform**: "Desktop"
**framework_version**: "0.15.6"
**obsidian_version**: "1.1.9"
**selected_service**: "bergamot"

**Comment by Fevol** [comment]
Thanks for the report,

I did indeed forego implementing the save functionality for the `Add & Update terms in both directions` toggle, but I can see how it could get annoying that it constantly resets.

I'll be fixing this up with the next release!

**Comment by Fevol** [comment]
Closing this issue as the feature is shipped with update [1.4.6](https://github.com/Fevol/obsidian-translate/releases/tag/1.4.6).
