### ISSUE TITLE
[BUG] Fanyi Baidu – ADD A TITLE HERE

### ISSUE THREAD

**Issue by egaojing** [Fevol/obsidian-translate#46]
# User report
**Description:** ADD A SHORT DESCRIPTION HERE 

---
# Debugger data (do not alter)
**plugin_version**: "1.4.4"
**platform**: "macOS"
**framework_version**: "1.1.9"
**obsidian_version**: "1.1.16"

**Comment by Fevol** [comment]
Closing this issue as it is an duplicate of #42.
