### ISSUE TITLE
Hotkey to open an existing Translate view

### ISSUE THREAD

**Issue by esm7** [Fevol/obsidian-translate#47]
Hey,

First thanks for an awesome plugin, I really needed that.
However, when trying to use Translate I ran into an issue. I put Translate in the sidebar, where I think it will be most beneficial for me, but when I use a hotkey or the command to open the Translate View, it won't go to the instance already in the sidebar but always open a new pane.
Is it possible to use an existing instance if one is already opened?
I added a GIF to better explain the issue.

Thanks in advance!

![Peek 2023-04-16 09-19](https://user-images.githubusercontent.com/10722656/232276538-61f35ce9-89e9-4622-9765-e3bf06a9c97f.gif)

**Comment by Fevol** [comment]
I apologize for the long wait. This feature has been implemented as the `Focus on translation view` command. It will focus on the input text area of the most recently opened Translation View (and show it if it is hidden). The update should be released soon.

**Comment by esm7** [comment]
That's really great news!

**Comment by Fevol** [comment]
The feature is finally shipped with update [1.4.6](https://github.com/Fevol/obsidian-translate/releases/tag/1.4.6), I keep saying this, but sorry for the wait! 😅

**Comment by esm7** [comment]
Thank you for shipping this!
The new command Focus on Translation View indeed focuses the view if one exists, but I can't get it to open the view if it is not currently shown. Am I doing something wrong?

**Comment by Fevol** [comment]
That was a design decision, but I can see how it makes sense that you would _want_ to open a translation view (either one that exists or open a new one). I've changed the code so it now opens a translation view when none exists (and still focuses on it).

Here's the latest build of the plugin with the fix: [translate.zip](https://github.com/Fevol/obsidian-translate/files/12302042/translate.zip)
(Fix is also pushed to repo, so you could compile yourself, if you so desire)

**Comment by Fevol** [comment]
Closing this issue as this has been fully released in [1.4.6](https://github.com/Fevol/obsidian-translate/releases/tag/1.4.6) (and in beta as [1.4.5](https://github.com/Fevol/obsidian-translate/releases/tag/1.4.5))
