### ISSUE TITLE
Hotkey to focus the source text box

### ISSUE THREAD

**Issue by esm7** [Fevol/obsidian-translate#48]
Hi,

I really want to integrate Translate into my keyboard-centric flow, and currently when opening the view, in order to start typing a word to translate I need to press Tab 4 times.
Is it possible to open the view with the 'Type here' box already focused and ready to go?

Thanks in advance!

**Comment by Fevol** [comment]
Will be shipped in the next update, the translation view will now always focus on the input text area on initially opening. With #47, you can also manually focus on the input text area with a hotkey.

**Comment by esm7** [comment]
Thank you, looking forward!

**Comment by Fevol** [comment]
Closing this issue as the fix is shipped with update [1.4.6](https://github.com/Fevol/obsidian-translate/releases/tag/1.4.6), sorry for the wait & thanks for the FR!

**Comment by esm7** [comment]
Thank you!
