### ISSUE TITLE
Translate to new line

### ISSUE THREAD

**Issue by chen-haobo** [Fevol/obsidian-translate#49]
Hello,
  I'd like that there is a  command that **translate to new line**，don't change the selection text，insert the translation to new line.

Thanks!

**Comment by Fevol** [comment]
Hey @chen-haobo , sorry for the wait with implementing this feature.
I've added a setting that allows you to set how you want your translation to be added into the text. You can find this setting here:

![image](https://github.com/Fevol/obsidian-translate/assets/8179397/d2703320-10b2-45af-88fe-a82527ea404a)

There are three options:
- "Replace input with translation" - This is the original setting, and will replace your selection with the translated text
- "Translation added below input" - The setting you proposed: it will add the selected text to the line below
- "Copy to clipboard" - Will save the translation to your clipboard, so you can paste it wherever you want

I know you asked for a separate command for doing this, is this still something you'd be interested in, or is this a sufficient solution for your workflow? Many thanks!

**Comment by Fevol** [comment]
Closing this issue as the feature is shipped with update [1.4.6](https://github.com/Fevol/obsidian-translate/releases/tag/1.4.6), please do re-open/reference this issue if you have more ideas for translation actions. Thanks again for the FR!
