### ISSUE TITLE
[Bug] Sync with spellchecker languages

### ISSUE THREAD

**Issue by kometenstaub** [Fevol/obsidian-translate#5]
After selecting the sync with spellchecker option, it

1. still shows the dropdown for selecting new languages, but doesn't work
2. after a restart of Obsidian, these languages are lost (not visible in the settings anymore, as well as missing from the sidebar pane

**Comment by Fevol** [comment]
1. Good catch! I was wondering, would you want the 'sync with spellchecker' to be read-only (i.e. you aren't able to select any other languages; the dropdown is completely hidden) or would you still like to be able to remove/add languages to that selection?
2. Can't believe I missed that, will be fixing that immediately!

**Comment by kometenstaub** [comment]
I think I'd expect not to be able to change them. But for the manual option, you could enable the spell-checker languages by default.
