### ISSUE TITLE
Paragraph breaks not preserved in lingva Eng-> japanese

### ISSUE THREAD

**Issue by ksdavidc** [Fevol/obsidian-translate#53]
Hi (long time no see). I haven't been using the plugin much lately for various reasons, but started up recently. One thing hanging me up is a snag with the lingva translator. It may not be with the plugin at all, but I find that in translating english to japanese, french and portuguese (the only languages I tested), paragraph breaks are not preserved, which was slowing me down.  I don't konw if it something fixable on your end, but I thought I'd let you know. Aside from that, hope you are doing well...

**Comment by Fevol** [comment]
Hey, I'm really sorry for the wait! I've tried fixing this a couple weeks before, but the lingva services seemed to be down. Apparently all `.ml` domains were taken offline, only 4 of the services still work.

Either way, I found the issue, and everything should work now, I forgot to properly encode the endline/paragraph breaks...

I'll be pushing this soon, thank you for reporting the issue! Sorry again for being so late with this, I've been getting distracted with the other plugin I've been working on 😅

**Comment by ksdavidc** [comment]
Hi, that's great. No worries about the time. I am a slow burner myself, and anyway I have my implicit trust.  Are you talking about criticmarkup? Nice idea! (though I wouldn't have call to use it.)

**Comment by Fevol** [comment]
Yep, the CriticMarkup plugin! Basically, I'm trying to squeeze Google Docs/Word's suggestion mode and comment system into Obsidian. It will be helpful for tracking changes, collaborating with people or leaving notes for yourself using pure markdown. There's still a lot of work left that needs to be done, but I'm getting closer and closer to a working product.

**Comment by Fevol** [comment]
Closing this issue as it is shipped with update [1.4.6](https://github.com/Fevol/obsidian-translate/releases/tag/1.4.6), thanks again for the issue report!

**Comment by ksdavidc** [comment]
Great. It works. 

FYI when I updated the plugin, reloading Obsidian didn't complete and I got one of those reboot or turn off community plugins messages. Eventually I had to reinstall the plugin from scratch and redo my settings, but it is working now beautifully, saving me a lot of time. Thanks!

**Comment by Fevol** [comment]
Agh, that should _never_ happen. Something may have gone wrong with the plugin's data when updating, though without error logs, it's hard to say. I'm sorry for that major inconvenience! Sometimes it feels like the plugin is barely held together by spit and baling wire. I'll be on the look-out for cases where this may happen.
