### ISSUE TITLE
[BUG] ADD A TITLE HERE

### ISSUE THREAD

**Issue by prechayimmee** [Fevol/obsidian-translate#57]
# User report
**Description:** ADD A SHORT DESCRIPTION HERE 

---
# Debugger data (do not alter)
**plugin_version**: "1.4.6"
**platform**: "iOS"
**framework_version**: "1.4.16 (114)"
**obsidian_version**: "1.4.16"
**selected_service**: "openai_translator"

**Comment by Fevol** [comment]
Thanks for the bug report, please provide more information about the issue by filling out the title and description. I'll re-open the comment once more information is provided.
