### ISSUE TITLE
[BUG] ADD A TITLE HERE

### ISSUE THREAD

**Issue by aazziizz-ii** [Fevol/obsidian-translate#58]
# User report
**Description:** ADD A SHORT DESCRIPTION HERE 

---
# Debugger data (do not alter)
**plugin_version**: "1.4.6"
**platform**: "Desktop"
**framework_version**: "1.4.16"
**obsidian_version**: "1.4.16"
**selected_service**: "google_translate"

**Comment by Fevol** [comment]
Thanks for the bug report, please provide more information about the issue by filling out the title and description. I'll re-open the issue once more information is provided.
