### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'action") (undefined)

### ISSUE THREAD

**Issue by DeverillRP** [Fevol/obsidian-translate#60]
# User report
**Description:** When I try to traslate something, either by right-clicking and using the context menu or by using the translation interface on a different tab, I get the following error:

**Translation failed:
Cannot read properties of undefined
(reading 'action") (undefined)**

When searching around for this kind of error, apparently people fix this by trying to find a conflicting community plugin. It could also be caused by a failure to find or access Obsidian files.

I have:
- tested my API key (Azure - and it functions for another translation software I use)
- tested another API Key (Google API, which I've only tested within the plugin's tool itself, and it turned OK)
- disabled every community plugin + resetting Obsidian + resetting the computer;
- double-checked for any lack of permissions for the plugin to access my vault;
- looked for an option to explicitly inform my vault location to the plugin.

This isn't urgent or anything, I really appreciate your contribution for this totally free resource. Please let me know if you need anything else!

---
# Debugger data (do not alter)
**plugin_version**: "1.4.6"
**platform**: "macOS"
**framework_version**: "1.4.16"
**obsidian_version**: "1.5.3"
**selected_service**: "azure_translator"

**Comment by DeverillRP** [comment]
I'm sorry, I was sure I had done this but I didn't try disabling the **core plugin "Note composer"**. After doing this, I'm able to translate stuff as intended.

Hopefully my mistake will be useful for someone else in the future.

**Comment by Fevol** [comment]
Thank you for your detailed explanations of the issue andwhat you tried, I very much appreciate it. I'm reopening the issue as this does seem like a rather significant issue, you really should not have to have to disable a Core plugin (or any plugin in general), in order to be able to translate.

**Comment by Fevol** [comment]
Re-closing this issue as I found the likely culprit for the error, and that specific message should not ever appear again.

Thanks again for bringing this to my attention!
