### ISSUE TITLE
How to use it with the Templator plugin?

### ISSUE THREAD

**Issue by OPEN1004MIND** [Fevol/obsidian-translate#63]
I've been using it quite well.
I have one request.

It would be nice if there was a way to use it in conjunction with the Templator plugin.

Example template expected conversion 
<%* 
let engTexg = "I want to translate"
targetText = { some action }
%>

It would be really useful to be able to do this.

**Comment by Fevol** [comment]
Thanks for the request, could you check if the following works for you?

```js
let engText = "I want to translate";
let sourceLanguage "auto";
let targetLanguage = "zh";

const translator = app.plugins.plugins['translate']?.translator;
let outputText = '';
if (translator && translator.valid) {
	outputText = await translator.translate(engText, sourceLanguage, targetLanguage).translation;
}
```

**Comment by OPEN1004MIND** [comment]
<%*
let engText = "I want to translate";
let sourceLanguage "auto";
let targetLanguage = "zh";

const translator = app.plugins.plugins['translate']?.translator;
let outputText = '';
if (translator && translator.valid) {
	outputText = await translator.translate(engText, sourceLanguage, targetLanguage).translation;
}
-%>
I don't know much about computer coding.
I tried this in a template format and got an error.
Do I need to do this as a JS file?

**Comment by Fevol** [comment]
I apologise for the delay, I wanted to fully fix the API before I investigated this further.

With the new version (releasing soon), you could make a template like this:
```ts
<%*
let engText = "I want to translate";
let sourceLanguage = "auto";  
let targetLanguage = "zh";

const api = app.plugins.plugins['translate'].api;
if (api?.canTranslate) {  
	const output = await api.translate(engText, sourceLanguage, targetLanguage); 
	console.log(output)
	if (output.status_code !== 200)
	    new Notice(output.message);
	else
	    tR += output.translation;
}
%>
```
(`tR` is what Templater will display, in this case)

Let me know if this (doesn't) work! Since I'm not very experienced with Templater myself, you may also want to ask in the Discord if there is a better/cleaner method.

**Comment by OPEN1004MIND** [comment]
Thank you very much.
code working fine
