### ISSUE TITLE
Feature suggestion: button to clear both panels

### ISSUE THREAD

**Issue by ksdavidc** [Fevol/obsidian-translate#64]
(Happy New Year. i. Long time, no see. I use this plugin almost daily and it has really helped me in my workflow. Thanks again for it.)

I had an idea for a useful feature to consider. You have button to clear the individual panels. I find that sometimes I wish there were a button to clear both panels at once, just to have a clean slate. I know it is not necessary, but it would be a little cleaner. Just a thought to consider.

**Comment by Fevol** [comment]
Thanks! Happy New Year to you too!

That does sound like an interesting feature, I'll have to look into a clean way for implementing it (probably a shortcut or quick action at the top bar).

Small note, though: it's probably going to take me a bit to get around to this. The plugin is in semi-maintenance mode as I'm currently spending all my spare time getting my other plugin finished finally. (Plus there are some fundamental issues of the plugin that need fixing, which will also cost a couple of days)

**Comment by ksdavidc** [comment]
No worries. I am happy as I am, and if it turns out not to be feasible/desirable/etc. not a problem.

**Comment by ksdavidc** [comment]
Basically working. Again, NOT A PRIORITY, but FYI: For me, this seems to work if the translate panel has translated results in it, but if I have typed somethign into the results panel, that does not get cleared (though original panel does). Also, I don't see a button, which is what I expected,but the hotkey works..

**Comment by Fevol** [comment]
The button doesn't get added automatically, as I felt that users would rather add it in themselves.

You can add it one of two ways:

1. By adding to to the 'quickaction defaults' in settings (which will add the button to every new translation view you open)

![image](https://github.com/Fevol/obsidian-translate/assets/8179397/a963dfa3-1427-40c0-b558-9d2b77f97fc8)

2.  By adding it in the view appearance settings

![image](https://github.com/Fevol/obsidian-translate/assets/8179397/d3f430d6-d963-4b7b-a8e2-c05af1ea68b7)


![image](https://github.com/Fevol/obsidian-translate/assets/8179397/6b94e0ed-794e-4387-8bd9-04af516f62c9)

**Comment by ksdavidc** [comment]
I had actually done all that :-) 

I figured it out. I was using the plugin from a tab that I had dragged to the right side of my vault. I opened a new translate tab in my main vault and then it had the button, and then I replaced the old tab in my side panel and the button was there. Still no luck on it deleting typed in text.
