### ISSUE TITLE
Last character of text will be removed

### ISSUE THREAD

**Issue by joethei** [Fevol/obsidian-translate#8]
See this gif: 
![gif](https://i.joethei.space/Obsidian_nKPSf9sYPz.gif)

This will only happen once after changing the text, clicking the translate icon after that will not do anything.

```txt
SYSTEM INFO:
	Obsidian version: v0.15.2
	Installer version: v0.14.6
	Operating system: Windows 10 Home 10.0.19043
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 7
	Safe mode: off
	Plugins installed: 34
	Plugins enabled: 3
		1: Hot Reload
		2: Obsidian42 - BRAT
		3: Translate - 1.1.4
```

**Comment by Fevol** [comment]
Thanks! Should be fixed in the latest release, let me know if you encounter any other issues

**Comment by joethei** [comment]
Perfect, thanks
